import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { render, run, voiceLevel } from '../scripts/build.mjs';

const REPO = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const { default: roster } = await import('../roster.mjs');

const RULES = 'FIXTURE-HOUSE-RULES-TEXT';
const files = {
  'shared/house-rules.md': RULES,
  'shared/voice/subtle.md': 'FIXTURE-VOICE-SUBTLE',
  'shared/voice/medium.md': 'FIXTURE-VOICE-MEDIUM',
  'shared/voice/full.md': 'FIXTURE-VOICE-FULL',
};
for (const a of Object.values(roster.agents)) {
  files[`roles/${a.role}.md`] = `ROLE BODY ${a.role}`;
  for (const p of a.personas) files[`personas/${p}.md`] = `PERSONA BODY ${p}`;
}
const readFile = (rel) => {
  if (!(rel in files)) throw Object.assign(new Error('nope'), { code: 'ENOENT' });
  return files[rel];
};

function frontmatter(md) {
  const m = md.match(/^---\n([\s\S]*?)\n---\n/);
  assert.ok(m, 'has frontmatter');
  return m[1];
}

test('frontmatter matches roster for every agent', () => {
  const out = render(roster, readFile);
  assert.deepEqual([...out.keys()].sort(), Object.keys(roster.agents).map((k) => `${k}.md`).sort());
  for (const [key, a] of Object.entries(roster.agents)) {
    const fm = frontmatter(out.get(`${key}.md`));
    assert.match(fm, new RegExp(`^name: ${key}$`, 'm'));
    assert.match(fm, new RegExp(`^tools: ${a.tools.join(', ').replace(/[()]/g, '\\$&')}$`, 'm'));
    assert.match(fm, new RegExp(`^model: ${a.model}$`, 'm'));
    assert.match(fm, new RegExp(`^effort: ${a.effort}$`, 'm'));
    assert.match(fm, new RegExp(`^color: ${a.color}$`, 'm'));
    const desc = fm.match(/^description: >\n((?:  .*\n?)+)/m)[1].split('\n').map((l) => l.trim()).join(' ').trim();
    assert.equal(desc, a.description);
  }
});

test('house rules, generated marker and identity line in every agent', () => {
  for (const [file, md] of render(roster, readFile)) {
    assert.ok(md.includes(RULES), `${file} has house rules`);
    assert.ok(md.includes('<!-- GENERATED by scripts/build.mjs'), `${file} has marker`);
    assert.match(md, /\nYou are .+ of the dojo crew — .+\.\n/);
  }
  assert.ok(render(roster, readFile).get('l.md').includes('You are L of the dojo crew'));
});

test('multi-persona agent has selection section and both personas', () => {
  const md = render(roster, readFile).get('strategist.md');
  assert.ok(md.includes('## Persona selection'));
  assert.ok(md.includes('dojo: on duty: <Name>'));
  assert.ok(md.includes('use Shikamaru.'));
  assert.ok(md.includes('PERSONA BODY shikamaru') && md.includes('PERSONA BODY lelouch'));
  assert.ok(md.includes('You are Shikamaru or Lelouch of the dojo crew'));
});

test('single-persona agent has no selection section', () => {
  const md = render(roster, readFile).get('senku.md');
  assert.ok(!md.includes('## Persona selection'));
  assert.ok(md.includes('PERSONA BODY senku'));
});

test('missing persona file errors clearly', () => {
  const partial = { ...files };
  delete partial['personas/lelouch.md'];
  assert.throws(
    () => render(roster, (rel) => { if (!(rel in partial)) throw Object.assign(new Error('x'), { code: 'ENOENT' }); return partial[rel]; }),
    /Missing persona "lelouch" file: personas\/lelouch\.md/,
  );
});

test('missing role file errors clearly', () => {
  const partial = { ...files };
  delete partial['roles/qa.md'];
  assert.throws(
    () => render(roster, (rel) => { if (!(rel in partial)) throw Object.assign(new Error('x'), { code: 'ENOENT' }); return partial[rel]; }),
    /Missing role "qa" file: roles\/qa\.md/,
  );
});

const VOICES = { subtle: 'FIXTURE-VOICE-SUBTLE', medium: 'FIXTURE-VOICE-MEDIUM', full: 'FIXTURE-VOICE-FULL' };

function assertOnlyVoice(md, level, label) {
  for (const [name, text] of Object.entries(VOICES)) {
    assert.equal(md.includes(text), name === level, `${label}: ${name} text ${name === level ? 'present' : 'absent'}`);
  }
}

test('default voice is medium: only its text is inserted, between persona and house rules', () => {
  assert.equal(roster.defaults.voice, 'medium');
  for (const [file, md] of render(roster, readFile)) {
    assertOnlyVoice(md, 'medium', file);
    const v = md.indexOf(VOICES.medium);
    assert.ok(md.lastIndexOf('PERSONA BODY') < v && v < md.indexOf(RULES), `${file}: voice sits after persona, before house rules`);
  }
});

test('every level inserts only its own text', () => {
  for (const level of Object.keys(VOICES)) {
    const out = render({ ...roster, defaults: { voice: level } }, readFile);
    for (const [file, md] of out) assertOnlyVoice(md, level, `${level}/${file}`);
  }
});

test('per-agent voice overrides the default', () => {
  const r = { ...roster, defaults: { voice: 'subtle' }, agents: { ...roster.agents, levi: { ...roster.agents.levi, voice: 'full' } } };
  const out = render(r, readFile);
  assertOnlyVoice(out.get('levi.md'), 'full', 'levi');
  assertOnlyVoice(out.get('senku.md'), 'subtle', 'senku');
  assert.equal(voiceLevel({}, 'x', {}), 'medium', 'falls back to medium with no defaults');
});

test('unknown voice level throws', () => {
  assert.throws(() => render({ ...roster, defaults: { voice: 'loud' } }, readFile), /unknown voice level "loud"/);
  const r = { ...roster, agents: { ...roster.agents, robin: { ...roster.agents.robin, voice: 'shouty' } } };
  assert.throws(() => render(r, readFile), /agent "robin": unknown voice level "shouty"/);
});

test('missing voice file errors clearly', () => {
  const partial = { ...files };
  delete partial['shared/voice/medium.md'];
  assert.throws(
    () => render(roster, (rel) => { if (!(rel in partial)) throw Object.assign(new Error('x'), { code: 'ENOENT' }); return partial[rel]; }),
    /Missing voice level "medium" file: shared\/voice\/medium\.md/,
  );
});

test('real sources: crew roles end with Says, strategist has Crew', () => {
  for (const role of ['backend', 'frontend', 'research-deep', 'research-quick', 'qa', 'docs']) {
    const body = fs.readFileSync(path.join(REPO, `roles/${role}.md`), 'utf8');
    assert.match(body, /\nSays: "<one in-character line, ≤20 words>"\n```/, `${role} contract ends with Says`);
  }
  assert.match(fs.readFileSync(path.join(REPO, 'roles/strategist.md'), 'utf8'), /\nCrew: .*`Says:` verbatim/);
});

function fixtureTree() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'dojo-test-'));
  fs.copyFileSync(path.join(REPO, 'roster.mjs'), path.join(root, 'roster.mjs'));
  for (const [rel, content] of Object.entries(files)) {
    fs.mkdirSync(path.dirname(path.join(root, rel)), { recursive: true });
    fs.writeFileSync(path.join(root, rel), content);
  }
  return root;
}

test('check mode: missing, clean, drifted, extra; no writes', async (t) => {
  const root = fixtureTree();
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));

  let r = await run({ root, check: true });
  assert.equal(r.ok, false);
  assert.equal(r.problems.filter((p) => p.startsWith('missing:')).length, Object.keys(roster.agents).length);
  assert.ok(!fs.existsSync(path.join(root, 'agents')), 'check does not write');

  await run({ root });
  r = await run({ root, check: true });
  assert.deepEqual(r.problems, []);
  assert.equal(r.ok, true);

  fs.appendFileSync(path.join(root, 'agents/senku.md'), 'tampered\n');
  fs.writeFileSync(path.join(root, 'agents/stale.md'), 'x');
  r = await run({ root, check: true });
  assert.deepEqual(r.problems.sort(), ['drifted: agents/senku.md', 'extra: agents/stale.md']);

  // write mode repairs drift and removes stale files
  await run({ root });
  assert.ok(!fs.existsSync(path.join(root, 'agents/stale.md')));
  assert.equal((await run({ root, check: true })).ok, true);
});

test('CLI honours --root and exit codes', (t) => {
  const root = fixtureTree();
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const cli = path.join(REPO, 'scripts/build.mjs');
  assert.equal(spawnSync('node', [cli, '--check', '--root', root]).status, 1);
  assert.equal(spawnSync('node', [cli], { env: { ...process.env, DOJO_ROOT: root } }).status, 0);
  assert.equal(spawnSync('node', [cli, '--check', '--root', root]).status, 0);
  fs.rmSync(path.join(root, 'personas/levi.md'));
  const bad = spawnSync('node', [cli, '--root', root], { encoding: 'utf8' });
  assert.equal(bad.status, 1);
  assert.match(bad.stderr, /Missing persona "levi" file/);
});

test('every real persona has Japanese lines & named moves with at least 4 well-formed entries', () => {
  const keys = [...new Set(Object.values(roster.agents).flatMap((a) => a.personas))];
  assert.equal(keys.length, 8);
  for (const key of keys) {
    const lines = fs.readFileSync(path.join(REPO, 'personas', `${key}.md`), 'utf8').split('\n');
    const at = lines.indexOf('Japanese lines & named moves:');
    assert.ok(at >= 0, `${key}: has section`);
    const entries = [];
    for (const l of lines.slice(at + 1)) {
      if (l.trim() === '') break;
      entries.push(l);
    }
    assert.ok(entries.length >= 4, `${key}: at least 4 entries (got ${entries.length})`);
    for (const e of entries) assert.match(e, /^- "[^"]+" \([^()]+\) — \S.*$/, `${key}: entry format: ${e}`);
    assert.ok(lines.length <= 55, `${key}: persona file stays within 55 lines`);
  }
});
