#!/usr/bin/env node
// Generates agents/*.md from roster.mjs + shared/ + personas/ + roles/.
//   node scripts/build.mjs [--check] [--root <dir>]     (root may also come from DOJO_ROOT)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const GENERATED = '<!-- GENERATED by scripts/build.mjs from roster.mjs — edit sources, not this file -->';

export function wrap(text, width = 76) {
  const lines = [];
  let cur = '';
  for (const word of text.trim().split(/\s+/)) {
    if (cur && cur.length + 1 + word.length > width) {
      lines.push(cur);
      cur = word;
    } else {
      cur = cur ? `${cur} ${word}` : word;
    }
  }
  if (cur) lines.push(cur);
  return lines;
}

export function displayName(roster, key) {
  const name = roster.displayNames?.[key];
  if (!name) throw new Error(`roster.displayNames has no entry for persona "${key}"`);
  return name;
}

export const VOICE_LEVELS = ['subtle', 'medium', 'full'];
export const DEFAULT_VOICE = 'medium';

/** Per-agent `voice` beats `roster.defaults.voice`, which beats 'medium'. Throws on an unknown level. */
export function voiceLevel(roster, key, agent) {
  const level = agent.voice ?? roster.defaults?.voice ?? DEFAULT_VOICE;
  if (!VOICE_LEVELS.includes(level)) {
    throw new Error(`agent "${key}": unknown voice level "${level}" (expected one of: ${VOICE_LEVELS.join(', ')})`);
  }
  return level;
}

/** Pure: roster + readFile(relPath)->string  =>  Map<'<key>.md', content>. */
export function render(roster, readFile) {
  const read = (rel, what) => {
    try {
      return String(readFile(rel)).trim();
    } catch (err) {
      if (err && err.code && err.code !== 'ENOENT') throw err;
      throw new Error(`Missing ${what} file: ${rel}`);
    }
  };

  const houseRules = read('shared/house-rules.md', 'house rules');
  const out = new Map();

  for (const [key, a] of Object.entries(roster.agents)) {
    for (const f of ['personas', 'role', 'model', 'effort', 'color', 'tools', 'description']) {
      if (a[f] == null || (Array.isArray(a[f]) && a[f].length === 0)) {
        throw new Error(`agent "${key}": missing required field "${f}"`);
      }
    }
    const names = a.personas.map((p) => displayName(roster, p));
    const personaBodies = a.personas.map((p) => read(`personas/${p}.md`, `persona "${p}"`));
    const level = voiceLevel(roster, key, a);
    const voiceBody = read(`shared/voice/${level}.md`, `voice level "${level}"`);
    const roleBody = read(`roles/${a.role}.md`, `role "${a.role}"`);

    const front = [
      '---',
      `name: ${key}`,
      'description: >',
      ...wrap(a.description).map((l) => `  ${l}`),
      `tools: ${a.tools.join(', ')}`,
      `model: ${a.model}`,
      `effort: ${a.effort}`,
      `color: ${a.color}`,
      '---',
    ].join('\n');

    const sections = [`You are ${names.join(' or ')} of the dojo crew — ${a.summary ?? a.role}.`];
    if (a.personas.length > 1) {
      sections.push(
        '## Persona selection',
        `A SessionStart line \`dojo: on duty: <Name>\` names the active persona. Use only that persona's voice sheet below for the whole session. If no such line is present, use ${names[0]}.`,
        ...personaBodies,
      );
    } else {
      sections.push(personaBodies[0]);
    }
    sections.push(voiceBody, houseRules, roleBody);

    out.set(`${key}.md`, `${front}\n\n${GENERATED}\n\n${sections.join('\n\n')}\n`);
  }
  return out;
}

export async function loadRoster(root) {
  const mod = await import(pathToFileURL(path.join(root, 'roster.mjs')).href);
  return mod.default;
}

/** Returns { ok, problems[], written[] }. In check mode nothing is written. */
export async function run({ root, check = false }) {
  const roster = await loadRoster(root);
  const rendered = render(roster, (rel) => fs.readFileSync(path.join(root, rel), 'utf8'));
  const dir = path.join(root, 'agents');
  const existing = fs.existsSync(dir) ? fs.readdirSync(dir).filter((f) => f.endsWith('.md')) : [];
  const stale = existing.filter((f) => !rendered.has(f));
  const problems = [];
  const written = [];

  if (check) {
    for (const [file, content] of rendered) {
      const p = path.join(dir, file);
      if (!fs.existsSync(p)) problems.push(`missing: agents/${file}`);
      else if (fs.readFileSync(p, 'utf8') !== content) problems.push(`drifted: agents/${file}`);
    }
    for (const f of stale) problems.push(`extra: agents/${f}`);
    return { ok: problems.length === 0, problems, written };
  }

  fs.mkdirSync(dir, { recursive: true });
  for (const [file, content] of rendered) {
    const p = path.join(dir, file);
    if (!fs.existsSync(p) || fs.readFileSync(p, 'utf8') !== content) {
      fs.writeFileSync(p, content);
      written.push(file);
    }
  }
  for (const f of stale) {
    fs.rmSync(path.join(dir, f));
    written.push(`${f} (removed)`);
  }
  return { ok: true, problems, written };
}

async function main() {
  const argv = process.argv.slice(2);
  const check = argv.includes('--check');
  const i = argv.indexOf('--root');
  const root = path.resolve(
    (i >= 0 && argv[i + 1]) || process.env.DOJO_ROOT || path.join(path.dirname(fileURLToPath(import.meta.url)), '..'),
  );
  try {
    const res = await run({ root, check });
    if (check) {
      if (res.ok) console.log('agents/ is up to date');
      else {
        console.error('agents/ is out of date — run `npm run build`:');
        for (const p of res.problems) console.error(`  ${p}`);
        process.exit(1);
      }
    } else {
      console.log(res.written.length ? `updated: ${res.written.join(', ')}` : 'agents/ already up to date');
    }
  } catch (err) {
    console.error(`build error: ${err.message}`);
    process.exit(1);
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) await main();
